# Generated by Django 3.2.4 on 2021-06-30 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210630_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='portfolioaction',
            name='completed_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='portfolioaction',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioaction',
            name='share_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioaction',
            name='total_value',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
