# Generated by Django 3.2.4 on 2021-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210822_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('USD', 'USD'), ('ILS', 'ILS')], max_length=9)),
                ('to_currency', models.CharField(choices=[('USD', 'USD'), ('ILS', 'ILS')], max_length=9)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
