# Generated by Django 3.2.4 on 2021-06-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210630_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
