# Generated by Django 3.2.4 on 2021-07-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210705_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioaction',
            name='total_cost',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='holding',
            name='cost_basis',
            field=models.FloatField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='holding',
            name='total_cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='holding',
            name='total_value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
