# Generated by Django 3.2.4 on 2021-08-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_portfolio_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
