# Generated by Django 3.2.4 on 2021-07-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210706_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='cost_basis',
            field=models.FloatField(blank=True),
        ),
    ]
