# Generated by Django 3.2.4 on 2021-07-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210706_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocomparison',
            name='asset_portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comparisons', to='api.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfoliocomparison',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_comparisons', to='api.portfolio'),
        ),
    ]
