# Generated by Django 3.2.4 on 2021-07-06 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_portfolio_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocomparison',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comparisons', to='api.profile'),
        ),
    ]
