# Generated by Django 3.2.4 on 2021-07-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210707_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioaction',
            name='total_value',
        ),
        migrations.AlterField(
            model_name='holding',
            name='total_value',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
