# Generated by Django 3.2.4 on 2021-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210708_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='total_value',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
