# Generated by Django 3.2.4 on 2021-07-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_portfolio_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='total_cost',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
