# Generated by Django 3.2.4 on 2021-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='currency',
            field=models.CharField(default='USD', editable=False, max_length=9),
        ),
        migrations.AddField(
            model_name='crypto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='five_year_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='location',
            field=models.CharField(default='Global', editable=False, max_length=9),
        ),
        migrations.AddField(
            model_name='crypto',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='one_year_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='one_year_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='one_year_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='six_month_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='three_month_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='three_year_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='type',
            field=models.CharField(default='Crypto', editable=False, max_length=9),
        ),
        migrations.AddField(
            model_name='crypto',
            name='ytd_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='israelpaper',
            name='currency',
            field=models.CharField(default='NIS', editable=False, max_length=9),
        ),
        migrations.AddField(
            model_name='israelpaper',
            name='five_year_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='israelpaper',
            name='location',
            field=models.CharField(default='Israel', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='israelpaper',
            name='one_year_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='israelpaper',
            name='six_month_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='israelpaper',
            name='three_month_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='israelpaper',
            name='three_year_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='israelpaper',
            name='ytd_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='book_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='business_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='currency',
            field=models.CharField(default='USD', editable=False, max_length=9),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='current_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='enterprise_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='five_year_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='forward_pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='fulltime_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='location',
            field=models.CharField(default='United States', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='mean_analyst_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='num_of_analysts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='one_year_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='one_year_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='one_year_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='peg_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='price_to_book',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='ps_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='revenue_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='six_month_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='three_month_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='three_year_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='trailing_pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uspaper',
            name='ytd_return',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
