# Generated by Django 3.2.4 on 2021-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_exchangerate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='short_url',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
